version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "80:80" # Assuming the client runs on port 3000 inside the container
    networks:
      - app_network
  server:
    build:
      context: ./server
    ports:
      - "4000:4000" # Assuming the server runs on port 4000 inside the container
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    networks:
      - app_network
networks:
  app_network:
    external: false
    name: app_network
