apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: HONEYCOMB_API_KEY
              value: FzKjzeQCaqicf1gIng8ffp
          image: server
          name: server
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
